//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cleaning
    {
        public int Id { get; set; }
        public Nullable<int> RoomId { get; set; }
        public Nullable<int> MaidId { get; set; }
    
        public virtual Maid Maid { get; set; }
        public virtual Room Room { get; set; }
    }
}
